name: ssipl_billing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  easy_sidemenu: ^0.6.0
  rowbuilder: ^0.0.1
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  syncfusion_flutter_pdfviewer: ^26.2.14
  dio: ^5.7.0
  dropdown_search: ^5.0.6
  multi_dropdown: ^2.1.4
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  pdf: ^3.11.1
  printing: ^5.13.2
  intl: ^0.19.0
  window_manager: ^0.4.2
  desktop_window: ^0.4.0
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  selectable_draggable_listbox: ^0.0.6
  excel: ^4.0.6
  file_saver: ^0.2.14
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^26.2.14
  table_calendar: ^3.1.2
  dashed_rect: ^0.0.4
  glowy_borders: ^1.0.2
  shared_preferences: ^2.3.5
  encrypt: ^5.0.3
  mime: ^2.0.0
  flutter_pdfview: ^1.4.0
  pdf_image_renderer: ^0.7.0
  pdf_render: ^1.4.7
  image: ^4.3.0
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/key.config
    - assets/images/
    - assets/pdf/
    - assets/fonts/
    - assets/fonts/Helvetica.ttf
    - assets/fonts/Helvetica-Bold.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: AbrilFatface
      fonts:  
        - asset: assets/fonts/AbrilFatface-Regular.ttf

